# Generated by Django 2.1.7 on 2019-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190219_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='field_service_url',
            field=models.URLField(),
        ),
    ]
